export enum FAVORITE_TYPES {
  GAMES = 'GAMES',
  MEALS = 'MEALS',
  MEMORIES = 'MEMORIES',
  MOVIES = 'MOVIES',
  MUSIC = 'MUSIC',
  PURCHASES = 'PURCHASES',
  READS = 'READS',
  SHOWS = 'SHOWS',
  SNEAKERS = 'SNEAKERS',
  SONGS = 'SONGS'
}

export const YEARS: string[] = ['2024', '2023', '2022', '2021', '2020', '2019'];

export enum SELECTION_TYPES {
  SELECTED_TYPE = 'SELECTED_TYPE',
  SELECTED_YEAR = 'SELECTED_YEAR'
}
